apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  labels:
    app: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login
          image: 'saketthakare/login:v1'
