apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  labels:
    app: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login
          image: 'thevarunjain/login:v1'
#          imagePullPolicy : Always
          env:
            - name: MONGO
              value: "mongodb://admin:admin@10.5.1.149:27017/?authSource=admin"