apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-service
  labels:
    app: timeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeline-service
  template:
    metadata:
      labels:
        app: timeline-service
    spec:
      containers:
        - name: timeline
          image: 'saketthakare/timeline:2.0'
          env:
          - name: RIAK_ENDPOINT
            value: "http://internal-riak-db-kohra-classic-697323016.us-east-1.elb.amazonaws.com"
          - name: POST_ENDPOINT
            value: "http://post-read.internal.landkarade.team/"
          - name: FOLLOWING_ENDPOINT
            value: "http://follow-read.internal.landkarade.team/"
