apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-service
  labels:
    app: timeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeline-service
  template:
    metadata:
      labels:
        app: timeline-service
    spec:
      containers:
        - name: timeline
          image: 'saketthakare/timeline:v1'
