apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-service
  labels:
    app: timeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeline-service
  template:
    metadata:
      labels:
        app: timeline-service
    spec:
      containers:
        - name: timeline
          image: 'vishumanvi/timeline:2.0'
          env:
          - name: RIAK_ENDPOINT
            value: "http://internal-riak-db-kohra-classic-697323016.us-east-1.elb.amazonaws.com"
          - name: POST_ENDPOINT
            value: "http://a38c7ef6d0c5011ea8c6f027917259c5-1701656662.us-east-1.elb.amazonaws.com/"
          - name: FOLLOWING_ENDPOINT
            value: "http://aa97379e40d9c11eaab3e0e836a5924b-530889720.us-east-1.elb.amazonaws.com/following/"
