apiVersion: v1
kind: Service
metadata:
  name: post-read-service
  labels:
    app: post-read-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: post-read-service