apiVersion: apps/v1
kind: Deployment
metadata:
  name: signup-service
  labels:
    app: signup-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signup-service
  template:
    metadata:
      labels:
        app: signup-service
    spec:
      containers:
        - name: signup
          image: 'thevarunjain/signup:v1'
#          imagePullPolicy : Always
          env:
            - name: MONGO
              value: "mongodb://admin:admin@10.5.1.149:27017/?authSource=admin"
