name: Build timeline docker image
on:
  push:
    paths:
      - 'services/timeline/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish timeline to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: saketthakare/timeline:v1
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./services/timeline