name: Build and Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Follow-Read to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: saketthakare/follow-read
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./services/follow-read